apiVersion: v1
kind: Pod
metadata:
  name: middlebox_kubernetes
  labels:
    app: middlebox-kubernetes
spec:
  restartPolicy: Always
  containers:
    - name: middlebox-kubernetes
      # Build this image from middleboxsgxshield.Dockerfile in this folder.
      image: middleboxsgxshield:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
      ports:
        - containerPort: 8443
          name: https-mb
          protocol: TCP
      volumeMounts:
        - name: dev-sgx-enclave
          mountPath: /dev/sgx_enclave
        - name: dev-sgx-provision
          mountPath: /dev/sgx_provision
        - name: certs-dir
          mountPath: /certs
  volumes:
    - name: dev-sgx-enclave
      hostPath:
        path: /dev/sgx_enclave
        type: CharDevice
    - name: dev-sgx-provision
      hostPath:
        path: /dev/sgx_provision
        type: CharDevice
    - name: certs-dir
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: middlebox-kubernetes
spec:
  selector:
    app: middlebox-kubernetes
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
