#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: ./generate_server_certs.sh [--force]

Generates the static certificate material required by PerformanceMeasuring/certs_server.py:
  ca.crt
  ca.key
  server/cert.pem
  server/key.pem

Delegated credentials are not generated here. The server creates dc.cred and
dckey.pem at runtime when the /certs endpoint is requested. This script does
validate the generated server certificate with DC/go/bin/go.

Options:
  --force   overwrite existing generated certificate files
  -h, --help
USAGE
}

force=0
while (($#)); do
    case "$1" in
        --force)
            force=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            printf 'Unknown option: %s\n\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CUSTOM_GOROOT="$PROJECT_ROOT/DC/go"
CUSTOM_GO="$CUSTOM_GOROOT/bin/go"
DC_GENERATOR="$CUSTOM_GOROOT/src/crypto/tls/generate_delegated_credential.go"
SERVER_DIR="$SCRIPT_DIR/server"
CONFIG_PATH="$SCRIPT_DIR/openssl_server.cnf"

if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required but was not found in PATH" >&2
    exit 1
fi

if [[ ! -x "$CUSTOM_GO" ]]; then
    echo "Custom Go not found or not executable: $CUSTOM_GO" >&2
    echo "Build the submodule first, then rerun this script." >&2
    exit 1
fi

if [[ ! -f "$DC_GENERATOR" ]]; then
    echo "Delegated credential generator not found: $DC_GENERATOR" >&2
    exit 1
fi

export GOROOT="$CUSTOM_GOROOT"
export PATH="$CUSTOM_GOROOT/bin:$PATH"

CA_CERT="$SCRIPT_DIR/ca.crt"
CA_KEY="$SCRIPT_DIR/ca.key"
CA_SERIAL="$SCRIPT_DIR/ca.srl"
SERVER_CERT="$SERVER_DIR/cert.pem"
SERVER_KEY="$SERVER_DIR/key.pem"
SERVER_CSR="$SERVER_DIR/server.csr"

DC_TMP_DIR=""

cleanup() {
    if [[ -n "$DC_TMP_DIR" && -d "$DC_TMP_DIR" ]]; then
        rm -f "$DC_TMP_DIR/dc.cred" "$DC_TMP_DIR/dckey.pem" "$DC_TMP_DIR/go-validation.log"
        rmdir "$DC_TMP_DIR" 2>/dev/null || true
    fi
}

trap cleanup EXIT

outputs=(
    "$CA_CERT"
    "$CA_KEY"
    "$CA_SERIAL"
    "$SERVER_CERT"
    "$SERVER_KEY"
    "$SERVER_CSR"
    "$CONFIG_PATH"
)

if [[ "$force" != "1" ]]; then
    existing=()
    for path in "${outputs[@]}"; do
        if [[ -e "$path" ]]; then
            existing+=("$path")
        fi
    done

    if ((${#existing[@]})); then
        echo "Certificate material already exists. Re-run with --force to overwrite:" >&2
        printf '  %s\n' "${existing[@]}" >&2
        exit 1
    fi
fi

mkdir -p "$SERVER_DIR"

cat >"$CONFIG_PATH" <<'CONFIG'
[req]
distinguished_name = req_dn
req_extensions = req_ext
prompt = no

[req_dn]
CN = server

[req_ext]
basicConstraints = CA:FALSE
extendedKeyUsage = serverAuth
subjectAltName = @san
keyUsage = critical, digitalSignature
1.3.6.1.4.1.44363.44 = DER:05:00

[san]
DNS.1 = server
DNS.2 = localhost
IP.1 = 127.0.0.1
CONFIG

openssl genrsa -out "$CA_KEY" 2048 >/dev/null 2>&1
openssl req \
    -x509 \
    -new \
    -nodes \
    -key "$CA_KEY" \
    -sha256 \
    -days 3650 \
    -subj "/CN=dcmb-local-ca" \
    -out "$CA_CERT" >/dev/null 2>&1

openssl genpkey -algorithm ED25519 -out "$SERVER_KEY" >/dev/null 2>&1
openssl req \
    -new \
    -key "$SERVER_KEY" \
    -out "$SERVER_CSR" \
    -config "$CONFIG_PATH" >/dev/null 2>&1

openssl x509 \
    -req \
    -in "$SERVER_CSR" \
    -CA "$CA_CERT" \
    -CAkey "$CA_KEY" \
    -CAcreateserial \
    -out "$SERVER_CERT" \
    -days 365 \
    -sha256 \
    -extfile "$CONFIG_PATH" \
    -extensions req_ext >/dev/null 2>&1

DC_TMP_DIR="$(mktemp -d)"
GO_VALIDATION_LOG="$DC_TMP_DIR/go-validation.log"
if ! (
    cd "$CUSTOM_GOROOT/src"
    go run crypto/tls/generate_delegated_credential.go \
        -cert-path "$SERVER_CERT" \
        -key-path "$SERVER_KEY" \
        -signature-scheme Ed25519 \
        -duration 168h \
        -out-path "$DC_TMP_DIR" >"$GO_VALIDATION_LOG" 2>&1
); then
    echo "Custom Go failed to validate delegated-credential generation." >&2
    sed -n '1,120p' "$GO_VALIDATION_LOG" >&2
    exit 1
fi

chmod 600 "$CA_KEY" "$SERVER_KEY"
chmod 644 "$CA_CERT" "$SERVER_CERT" "$SERVER_CSR" "$CONFIG_PATH"
[[ -f "$CA_SERIAL" ]] && chmod 644 "$CA_SERIAL"

echo "Generated local certificate material:"
echo "  $CA_CERT"
echo "  $SERVER_CERT"
echo "  $SERVER_KEY"
echo
echo "Validated delegated-credential generation with: $CUSTOM_GO"
echo "Runtime delegated credentials will be generated by certs_server.py."
