FROM ubuntu:22.04

# Installa tool necessari
RUN apt-get update && apt-get install -y \
    bash git curl tar build-essential ca-certificates iputils-ping python3 python3-pip  
    #bash git curl tar build-essential ca-certificates iputils-ping 
    #&& rm -rf /var/lib/apt/lists/*

WORKDIR /root

# Copia il Go custom pre-compilato del professore
COPY DC/go /root/go

# Aggiorna il PATH per usare il Go custom
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/go/bin
ENV GOROOT=/root/go
ENV GOMODCACHE=/root/go/pkg/mod
ENV GOPATH=/root/go

RUN python3 -m pip install --user requests

# # Copia il codice del middlebox
WORKDIR /certs

# cosa fa? si può evitare? inserita per gsc
RUN mkdir -p /certs && touch /certs/cert.pem /certs/key.pem

WORKDIR /app 
COPY DC/Middlebox/middlebox.go .
COPY DC/Middlebox/middleboxHandler.go .
COPY DC/Middlebox/messageTypes.go .
# Inserito per gsc
COPY DC/Middlebox/jwks.dat .
COPY DC/Middlebox/go.mod .
COPY DC/Middlebox/go.sum .

#COPY PerformanceMeasuring/certs_ServerToMiddlebox.py .

#COPY . .
#COPY Middlebox/middlebox.go .
#COPY Middlebox/go.mod .
#COPY Middlebox/go.sum .

# Compila il middlebox usando il Go custom
RUN GOOS=linux GOARCH=amd64 /root/go/bin/go build -o middlebox middlebox.go middleboxHandler.go messageTypes.go
#RUN go mod tidy && GOOS=linux GOARCH=amd64 go build -o client client.go

 

#RUN go run ~/go/src/crypto/tls/generate_cert.go -host 127.0.0.1 -allowDC
#RUN go run ~/go/src/crypto/tls/generate_delegated_credential.go -cert-path cert.pem -key-path key.pem -signature-scheme Ed25519 -duration 168h

#RUN env GOOS=linux GOARCH=amd64 go build -v -x -o middlebox middlebox.go middleboxHandler.go messageTypes.go

# # Comando di avvio
#CMD ["./middlebox"]
# oppure 
#CMD [/bin/bash]



#COPY certs_from_server.py .
#COPY certs_to_middlebox.py .
#RUN python3 certs_from_server.py 
#RUN python3 certs_to_middlebox.py