LoadModule proxy_module /home/bonsai/dcmb/.tlmsp/libexec/apache24/mod_proxy.so
LoadModule proxy_http_module /home/bonsai/dcmb/.tlmsp/libexec/apache24/mod_proxy_http.so

AcceptFilter https none

Listen 127.0.0.1:4444 https

<VirtualHost 127.0.0.1:4444>
    ServerName localhost
    SSLEngine on

    SSLCertificateFile "/home/bonsai/dcmb/.tlmsp/etc/pki/server-cert.pem"
    SSLCertificateKeyFile "/home/bonsai/dcmb/.tlmsp/etc/pki/private/server-key.pem"
    TLMSPConfigFile "/home/bonsai/dcmb/ETSI/Configurations/local_init.ucl"

    ProxyPassMatch "^/(.*)$" "http://127.0.0.1:7000/$1"
    ProxyPassReverse "/" "http://127.0.0.1:7000/"
</VirtualHost>
